module.exports = {
  content: [
    "./renderer/index.html",
    "./renderer/src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
        colors: {
          surface: 'var(--surface, #131313)',
          'surface-container': 'var(--surface-container, #201f1f)',
          'surface-container-low': 'var(--surface-container-low, #1c1b1b)',
          'surface-container-high': 'var(--surface-container-high, #2a2a2a)',
          'surface-container-highest': 'var(--surface-container-highest, #353534)',
          'surface-container-lowest': 'var(--surface-container-lowest, #0e0e0e)',
          'surface-dim': 'var(--surface-dim, #131313)',
          'surface-bright': 'var(--surface-bright, #3a3939)',
          'surface-variant': 'var(--surface-variant, #353534)',
          'on-surface': 'var(--on-surface, #ffffff)',
          'on-surface-variant': 'var(--on-surface-variant, #f0f4ef)',
          primary: 'var(--primary, #00f6f6)',
          'primary-container': 'var(--primary-container, #003737)',
          'on-primary-container': 'var(--on-primary-container, #00fbfb)',
          'on-primary': 'var(--on-primary, #001414)',
          'primary-fixed': 'var(--primary-fixed, #00fbfb)',
          'primary-fixed-dim': 'var(--primary-fixed-dim, #00dddd)',
          'on-primary-fixed': 'var(--on-primary-fixed, #001414)',
          'on-primary-fixed-variant': 'var(--on-primary-fixed-variant, #00fbfb)',
          secondary: 'var(--secondary, #ffabf3)',
          'secondary-container': 'var(--secondary-container, #500050)',
          'on-secondary-container': 'var(--on-secondary-container, #ffabf3)',
          'secondary-fixed': 'var(--secondary-fixed, #ffd7f5)',
          'secondary-fixed-dim': 'var(--secondary-fixed-dim, #ffabf3)',
          'on-secondary-fixed': 'var(--on-secondary-fixed, #380038)',
          'on-secondary-fixed-variant': 'var(--on-secondary-fixed-variant, #810081)',
          tertiary: 'var(--tertiary, #e6fffe)',
          'tertiary-container': 'var(--tertiary-container, #00f6f6)',
          'on-tertiary-container': 'var(--on-tertiary-container, #006d6d)',
          'tertiary-fixed': 'var(--tertiary-fixed, #00fbfb)',
          'tertiary-fixed-dim': 'var(--tertiary-fixed-dim, #00dddd)',
          'on-tertiary-fixed': 'var(--on-tertiary-fixed, #002020)',
          'on-tertiary-fixed-variant': 'var(--on-tertiary-fixed-variant, #004f4f)',
          error: 'var(--error, #ffb4ab)',
          'error-container': 'var(--error-container, #93000a)',
          'on-error': 'var(--on-error, #690005)',
          'on-error-container': 'var(--on-error-container, #ffdad6)',
          outline: 'var(--outline, #00f6f6)',
          'outline-variant': 'var(--outline-variant, #00f6f6)',
          'inverse-surface': 'var(--inverse-surface, #e5e2e1)',
          'inverse-on-surface': 'var(--inverse-on-surface, #313030)',
          'inverse-primary': 'var(--inverse-primary, #00fbfb)',
          brand: {
            500: 'var(--primary, #00f6f6)',
            600: 'var(--primary-fixed-dim, #00dddd)',
            400: 'var(--primary-fixed, #00fbfb)',
          },
          slate: {
            950: '#0e0e0e',
            900: '#131313',
            800: '#201f1f',
            700: '#2a2a2a',
            600: '#353534',
            500: '#717171',
            400: '#a0a0a0',
            300: '#d1d1d1',
            200: '#e5e2e1',
            100: '#f0f4ef',
            50: '#ffffff',
          }
      }
    },
  },
  plugins: [],
}
